
# dataset and data loader settings
name: TPCNet_VILNC
dataname: VILNC
resume: False

datasets:
  train:
    dateset_opt:
      type: VILNCDatasetFromFolder
      data_dir: E:\Open_source\Anonymous_TPCNet\Test_dataset\VILNC_Indoor\Train
      filp: True
      crop_size: 320
    loader_opt:
      batch_size: 8
      shuffle: True
  eval:
    dateset_opt:
      type: VILNCDatasetFromFolder
      data_dir: E:\Open_source\Anonymous_TPCNet\Test_dataset\VILNC_Indoor\Test
      #fold_name:
    loader_opt:
      batch_size: 1
      shuffle: False

network:
  type: TPCNet
  CAM_type: YCBCR

train:
  num_gpu: 1
  total_epoch: 1500
  warmup_epoch: 3 # -1 no warm up
  use_grad_clip: False
  Idx: False  #add the idx to the saved image making sure image matching
  saveGT: False
  target_path: E:\Open_source\Anonymous_TPCNet\Test_dataset\VILNC_Indoor\Test\Normal

  optim_opt:
    type: Adam
    lr: !!float 2.2e-4
    # weight_decay: !!float 1e-4
    # betas: [ 0.9, 0.999 ]

  scheduler:
    type: CosineAnnealingRestartLR
    restart_weights: [1]
    eta_min: !!float 1e-7

  loss_fn:
    L1_weight: !!float 1.0
    D_weight: !!float 0.0
    E_weight: !!float 15
    P_weight: !!float 0.1
    Color: !!float 0.1

#eval:
#  color_transition:
#    alpha_color: 0.8

logger:
  save_freq: 10
  use_tb_logger: true

